#!/bin/sh
# Minimal namespace sandbox using unshare & setpriv from util-linux.
# GH: @sandbox-utils/sandbox-run
# shellcheck disable=SC2093,SC2317
set -eu

ROOT="${ROOT:-$PWD/.sandbox}" ROOT="${ROOT%%/}"
VERBOSE="${VERBOSE:-}"
CLEANUP="${CLEANUP:-}"
RO_BIND="${RO_BIND-}"
RW_BIND="${RW_BIND-}"

DEFAULT_RO_BIND="${DEFAULT_RO_BIND-\
/etc/alternatives
/etc/hosts
/etc/ld.so.cache
/etc/localtime
/etc/os-release
/etc/pkcs11
/etc/pki
/etc/resolv.conf
/etc/ssl
/etc/timezone
/lib
/lib64
/run/dbus/system_bus_socket
/usr
}"

# ld.so.conf.d: https://containertoolbx.org/doc/#ldconfig8
DEFAULT_RW_BIND="${DEFAULT_RW_BIND-\
/etc/ld.so.conf.d
}"

_RS="$(printf '\036')"
_LF="$(printf '\012')"
pwd="$PWD"

_split_str () { printf '%s' "$1" | case "$1" in *$_LF*) tr '\n' "$_RS" ;; *) tr ' ' "$_RS" ;; esac; }

verbose_stdout () { if [ "$VERBOSE" ]; then cat >&2; else cat >/dev/null; fi }

_cleanup () {
    {
        echo; echo; echo "[${0##*/}]: Cleanup ..."
        # Clean up slirp4netns if we started it
        if [ "${slirp_pid-}" ]; then
            kill "$slirp_pid" || true
            # shellcheck disable=SC2015
            sleep 0.1 && kill -KILL "$slirp_pid" 2>/dev/null || true &
        fi

        umount -vR "$ROOT/dev" "$ROOT/$pwd" 2>&1
        mount_points="$(mount | grep -F "$ROOT" | cut -d' ' -f3 | sort -r)"
        echo "$mount_points" | xargs -r umount -vR 2>&1

        cd "$ROOT"
        [ ! "${seccomp_filter_cleanup:-}" ] || rm -v "seccomp_filter.bin"
        [ ! "${slirp_socket-}" ] || rm -vf "$slirp_socket" || true
        rm -vf bin sbin || true  # Symlinks
        IFS="$_RS"
        # shellcheck disable=SC2046
        find $(_split_str "$mount_points") -type f -empty -print0 | xargs -0r rm  # touch-ed files
        rm -vf ./etc/passwd ./etc/group  # Created /etc
        find . -type d -empty -delete
        ! command -v tree 2>/dev/null || tree --dirsfirst -hfaL4 .
        cd -

        if [ "$CLEANUP" ]; then rm -rfv "$ROOT"
        elif [ "$VERBOSE" ]; then echo "sandbox-run: rootfs workdir in \"$ROOT\"" >&2
        fi
    } 2>&1 | verbose_stdout
}

_mount_path () {
    src="$1" dst="${2:-$1}" ro="${3:+,ro}"
    if [ -d "$src" ]; then
        mount --mkdir -vo "rbind${ro:+,ro=recursive}" "$src" ".$dst"
    elif [ -e "$src" ]; then
        mkdir -p ".${dst%/*}"
        touch ".$dst" || true
        mount -vo "bind$ro" "$src" ".$dst"
    fi
}

_mount_bind () (
    spec="$1" ro="${2:-}"
    # shellcheck disable=SC2086
    _mount_path \
        "$(cd "$pwd"; realpath "${spec%%:*}")" \
        "$(cd "$pwd"; realpath "${spec#*:}")" $ro
)

_generate_seccomp_filter () {
    command -v enosys >/dev/null || return
    tmp1="$(mktemp)" tmp2="$(mktemp)"
    enosys --list | awk '{ print $2 }' | sort -u > "$tmp1"
    # "Dangerous" syscalls. File a bug if the list seems too strict.
    echo "\
add_key
adjtimex
afs_syscall
bpf
clock_adjtime
clock_settime
create_module
delete_module
finit_module
get_kernel_syms
init_module
ioperm
iopl
io_uring_enter
io_uring_register
io_uring_setup
kcmp
kexec_file_load
kexec_load
keyctl
lookup_dcookie
mbind
migrate_pages
mknod
mknodat
mlockall
modify_ldt
move_pages
nfsservctl
perf_event_open
process_vm_readv
process_vm_writev
ptrace
query_module
reboot
request_key
sched_setaffinity
sched_setattr
sched_setparam
sched_setscheduler
security
setdomainname
sethostname
set_mempolicy
set_mempolicy_home_node
settimeofday
swapoff
swapon
sysfs
syslog
tuxcall
uselib
userfaultfd
vhangup
vserver" | sort -u > "$tmp2"
    # shellcheck disable=SC2046
    enosys --dump="$ROOT/seccomp_filter.bin" \
        $(comm -12 "$tmp1" "$tmp2" | awk '{ printf " --syscall %s", $0}')
    rm "$tmp1" "$tmp2"
    seccomp_filter_cleanup=1
}

_read_firejail_config () {
    tmp="./.tmp"
    cat_profile () { [ ! -e "$1" ] || grep -E 'noblacklist|include|read-only' "$1"; }
    cat_profile "./firejail.profile" >"$tmp"
    exec 3<"$tmp"
    while read -r line <&3 || [ "$line" ]; do
        keyword="${line%% *}"
        pth="${line#* }" pth="${pth%% *}"
        echo "pth = $pth; $keyword -- $line"
        # shellcheck disable=SC1083
        case "$pth" in
            *\${HOME}*) eval "pth=$pth" ;;
            *\${PATH}*)
                exe="${pth##*/}"
                IFS=:; for dir in $PATH; do
                    # shellcheck disable=SC2015
                    [ -x "$dir/$exe" ] && pth="$dir/$exe" && break || true
                done
                ;;
        esac
        case "$keyword" in
            include) cat_profile "$(cd /etc/firejail; realpath "$pth")" >>"$tmp"; continue ;;
        esac
        for path in $pth; do
            [ "$keyword" = 'read-only' ] && ro=1 || ro=
            _mount_path "$path" '' $ro
        done
    done
    exec 3<&-
    rm "$tmp"
}

_sandbox_init () {
    # Prepare chroot
    # XXX: Ideally we would set up overlayfs with lower=/,upper=$ROOT, but for permissions ...
    mkdir -p "$ROOT"
    trap _cleanup EXIT TERM INT HUP

    # Source .env
    [ ! -e "$pwd/.env" ] || {
        . "$pwd/.env"
        # shellcheck disable=SC2013
        for var in $(grep -oP '^\w+' "$pwd/.env"); do export "${var?}"; done
    }
    # Init the environment passed via fd, which overrides .env
    # $ VAR=1 sandbox-run cmd  # overrides VAR from .env
    set -f; IFS="$_RS"
    # shellcheck disable=SC2013
    for var in $(cat <&5); do export "${var?}"; done
    unset IFS; set +f

    self="$(case "$0" in /*) echo "$0" ;; *) realpath "$0" ;; esac)"
    {
        cd "$ROOT"
        mkdir -vp dev proc sys tmp etc usr lib lib64 opt root var .git ".$HOME" ".$pwd"

        # Mock /dev
        # Make sure filesystem superblock is owned by a mapped UID (i.e. 65534 -> 0)
        mount -t tmpfs -vo mode=0755,dev tmpfs dev
        mkdir -vp dev/pts dev/shm dev/fd
        mount -t devpts -o "newinstance,ptmxmode=0666" devpts dev/pts
        mount -t tmpfs tmpfs dev/shm
        for pth in dev/zero dev/null dev/full dev/random dev/urandom dev/tty dev/console; do
            if [ -e "/$pth" ]; then
                # shellcheck disable=SC2015
                [ -d "/$pth" ] && mkdir "$pth" || touch "$pth"
                mount -vo rbind,uid=0,gid=0,dev "/$pth" "$pth"
            fi
        done
        ln -vs /dev/pts/ptmx dev/ptmx
        ln -vs /proc/kcore dev/core
        ln -vs /proc/self/fd dev/fd
        ln -vs /proc/self/fd/0 dev/stdin
        ln -vs /proc/self/fd/1 dev/stdout
        ln -vs /proc/self/fd/2 dev/stderr
        for i in 0 1 2; do
            ln -vs /proc/self/fd/$i dev/fd/$i
        done

        # Mount default dirs, usr, lib
        IFS="$_RS"
        for pth in $(_split_str "$DEFAULT_RW_BIND"); do
            [ ! -e "$pth" ] || _mount_path "$pth" ''
        done
        for pth in $(_split_str "$DEFAULT_RO_BIND"); do
            [ ! -e "$pth" ] || _mount_path "$pth" '' ro
        done
        unset IFS

        # sandbox-run script itself required for payload stage
        [ -x ".$self" ] || _mount_bind "$self" ro

        # /etc
        getent group nogroup > etc/group
        getent passwd root "$USER" > etc/passwd

        # Mount CWD
        mount -v --rbind "$pwd" ".$pwd"
        # Overlay some resources with empty/null to conceal them
        mkdir -vp .empty-sandbox .empty-git
        mount -v --bind .empty-sandbox ".$pwd/${ROOT##*/}"
        find "$pwd" -path "$ROOT" -prune -o -type d -name '.git' -print0 |
            xargs -0r mount -v --bind .empty-git
        find "$pwd" -path "$ROOT" -prune -o -type f -name '.env' -print0 |
            xargs -0r mount -v --bind /dev/null

        # Handle RW_BIND=, RO_BIND=
        IFS="$_RS"
        for pth in $(_split_str "${RW_BIND:-}"); do
            _mount_bind "$pth"
        done
        for pth in $(_split_str "${RO_BIND:-}"); do
            _mount_bind "$pth" ro
        done
        unset IFS

        # Symlinks: /bin -> /usr/bin ...
        for pth in usr/bin usr/sbin; do
            [ -e "${pth##*/}" ] || ln -vs "$pth" "${pth##*/}"
        done

        # Read firejail profile(s), if available
        [ ! -e "./firejail.profile" ] || _read_firejail_config
    } 2>&1 | verbose_stdout

    # Install seccomp filter if available
    [ -e "$ROOT/seccomp_filter" ] || _generate_seccomp_filter

    # Don't pass these variables to sandbox
    unset RO_BIND RW_BIND
    unset DEFAULT_RO_BIND DEFAULT_RW_BIND

    # Support symlinks e.g. ./local/bin/npm -> /usr/bin/sandbox-run
    if [ "${0##*/}" != 'sandbox-run' ]; then
        IFS=:
        for d in ${PATH:-/usr/local/bin:/usr/bin:/bin}; do
            p="$d/${0##*/}"
            # shellcheck disable=SC2015
            [ "$0" != "$p" ] && [ -x "$p" ] && set "$p" "$@" && break || true
        done
        unset IFS
    elif [ "$#" -eq 0 ]; then
        # If no args, run default shell
        # shellcheck disable=2015
        command -v bash >/dev/null 2>&1 && set bash || set sh
    fi

    # TODO: Set cgroup-based CPU use limit
    # https://unix.stackexchange.com/questions/151883/limiting-processes-to-not-exceed-more-than-10-of-cpu-usage/193996#193996

    # Set netns via slirp4netns
    hostname sandbox-run
    command -v slirp4netns >/dev/null 2>&1 && netns=--net || netns=

    # Switch into a nobody:nogroup namespace
    [ -t 0 ] && keep_tty='/dev/tty' || keep_tty='/dev/fd/0'
    random_time_offset="$(( ($(date +%s) % 32768) * ($(date +%s) % 101) ))"
    [ -e "$ROOT/seccomp_filter.bin" ] && seccomp_filter="/seccomp_filter.bin" || seccomp_filter=
    # shellcheck disable=2086
    unshare \
        --kill-child --mount-proc --mount-binfmt \
        --map-user "$USER" --map-group nogroup \
        --monotonic $random_time_offset --boottime $random_time_offset \
        --ipc --mount $netns --pid --uts --user --cgroup --time \
        --keep-caps --root "$ROOT" --wd "$pwd" \
        setpriv ${seccomp_filter:+--seccomp-filter "$seccomp_filter"} \
            --bounding-set=-all,+NET_RAW \
            --inh-caps=-all,+NET_RAW \
            --ambient-caps=-all,+NET_RAW \
        "$0" --_sandbox_payload "$@" <"$keep_tty" &
    unshare_pid=$!

    # Netns configuration
    i=0
    while [ $i -lt 500 ]; do
        [ ! -e "/proc/$unshare_pid/ns/net" ] || break
        i=$((i+1))
        sleep 0.01
    done
    if [ "$netns" ]; then
        fifo="$(mktemp -u)"; mkfifo "$fifo"
        tapname="tap-pid-$unshare_pid=$(echo "$*" | tr -cs '[:alnum:]' '-')"
        [ "${PORTS:-}" ] && slirp_socket="$ROOT/slirp4netns.sock" || slirp_socket=
        slirp4netns --configure --mtu=65520 --enable-ipv6 --enable-sandbox --disable-host-loopback \
            ${slirp_socket:+--api-socket "$slirp_socket"} \
            "$unshare_pid" "$tapname" >"$fifo" 2>&1 &
        slirp_pid=$!
        verbose_stdout <"$fifo" &
        rm "$fifo"
    fi

    # Wait for the sandbox payload to finish
    wait "$unshare_pid"
    exit_status=$?

    exit $exit_status
}

_sandbox_payload () {
    # Inside the sandbox, run
    echo "[${0##*/}] uid:$(id -u) pid:$$ cwd:$PWD args: $*"

    # Set up port forwarding
    [ ! "${PORTS-}" ] || [ -e /slirp4netns.sock ] || ! command -v slirp4netns >/dev/null 2>&1
    for spec in $(echo "${PORTS-}" | tr ',' ' '); do
        host_port="${spec%%:*}" t=${spec#*:} guest_port=${t%%/*}
        proto=${t#"$guest_port"} proto=${proto#/}
        printf '{"execute":"add_hostfwd","arguments":{"proto":"%s","host_port":%d,"guest_port":%d}}' "${proto:-tcp}" "$host_port" "$guest_port" |
            nc -w 1 -U /slirp4netns.sock
    done
    unset PORTS

    [ ! "$VERBOSE" ] || env | sort
    exec "$@"
}

_filter_env () {
    env -0 | grep -Eze '^('\
'VERBOSE|CLEANUP|RO_BIND|RW_BIND|DEFAULT_RO_BIND|DEFAULT_RW_BIND|PORTS|'\
'USER|LOGNAME|UID|PATH|TERM|HOME|HOSTNAME|DISPLAY|WAYLAND_DISPLAY|'\
'LANGUAGE|LANG|LC_[^= ]*|TZ|'\
'https?_proxy|HTTPS?_PROXY|'\
'CC|CFLAGS|CXXFLAGS|CPPFLAGS|LDFLAGS|LDLIBS|MAKEFLAGS|'\
'NODE_OPTIONS)='
}

case "${1:-}" in
    --_sandbox_init) shift 1; _sandbox_init "$@"; exit $?; ;;
    --_sandbox_payload) shift 1; _sandbox_payload "$@"; exit $?; ;;
    -h|--help|-?)
        if [ "${0##*/}" = 'sandbox-run' ]; then  # Else: --help refers to "npm"
            echo "Usage: $0 [CMD [ARGS...]]"; echo
            echo 'Sandbox a Linux program. https://github.com/sandbox-utils/sandbox-run'
            exit 1
        fi ;;
esac

# We switch into a root-user namespace where mount is allowed
# Keep --net namespace; unshare it in the next stage.
env -i \
    unshare \
    --kill-child --mount-proc --mount-binfmt --map-root-user \
    --monotonic -1000 --boottime -1000 \
    --ipc --mount --pid --uts --user --cgroup --time \
    "$0" --_sandbox_init "$@" \
    5<<EOF
$(_filter_env | tr '\0' "$_RS")
EOF

exit 0
