name: CI
on:
  push:
    branches: [master]
    tags: ['v*']
  pull_request: { branches: [master] }
  schedule: [ cron: '9 5 7 * *' ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - run: shellcheck -S warning sandbox-run tests/*.sh
      - run: |
          sudo sysctl -w kernel.unprivileged_userns_clone=1
          # sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=1
          # sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=1
      - run: sudo apt-get install tree man-db-
      - run: time bash tests/smoke-test.sh
      - run: time bash tests/test-bwrap-opts.sh
      - run: time bash tests/test-env-vars.sh
      - run: time bash tests/test-npm.sh
      - run: time bash tests/test-symlinks.sh

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@f72ff1a1336129f29bf0166c0fd0ca6cf1bcb38c  # v1.2.1
